// Copies contract ABIs (from `forge build`) and the testnet deployment into the app and scripts,
// as `as const` literals so viem can type every call.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const root = join(import.meta.dirname, '..');
const out = join(root, 'contracts/out');
const target = join(root, 'app/src/generated');
mkdirSync(target, { recursive: true });

// export name -> [source file, contract]
const contracts: Record<string, [string, string]> = {
  dividendIndexAbi: ['DividendIndex', 'DividendIndex'],
  factoryAbi: ['ExdivFactory', 'ExdivFactory'],
  vaultAbi: ['ExdivVault', 'ExdivVault'],
  exdivTokenAbi: ['ExdivTokens', 'ExdivToken'],
  bookAbi: ['ExdivBook', 'ExdivBook'],
  routerAbi: ['ExdivRouter', 'ExdivRouter'],
  mockStockTokenAbi: ['MockStockToken', 'MockStockToken'],
  demoStockAbi: ['DemoStockToken', 'DemoStockToken'],
};

let ts = '// Generated by scripts/export-abis.ts from contracts/out. Do not edit.\n\n';
for (const [name, [source, contract]] of Object.entries(contracts)) {
  const file = join(out, `${source}.sol`, `${contract}.json`);
  const { abi } = JSON.parse(readFileSync(file, 'utf8'));
  ts += `export const ${name} = ${JSON.stringify(abi, null, 2)} as const;\n\n`;
}
writeFileSync(join(target, 'abis.ts'), ts);

// The deployment record, plus the L2 block it started at. (On Arbitrum chains `block.number` inside a contract is
// an L1 estimate, so the block comes from forge's broadcast receipts instead.)
const deploymentFile = join(root, 'contracts/deployments/robinhood-testnet.json');
const broadcast = join(root, 'contracts/broadcast/Deploy.s.sol/46630/run-latest.json');
if (existsSync(deploymentFile)) {
  const deployment = JSON.parse(readFileSync(deploymentFile, 'utf8'));
  if (existsSync(broadcast)) {
    const { receipts } = JSON.parse(readFileSync(broadcast, 'utf8'));
    deployment.deployedAtBlock = Math.min(...receipts.map((r: { blockNumber: string }) => Number(r.blockNumber)));
    writeFileSync(deploymentFile, JSON.stringify(deployment, null, 2) + '\n');
  }
  writeFileSync(join(target, 'deployment.json'), JSON.stringify(deployment, null, 2) + '\n');
}
console.log(`wrote ${Object.keys(contracts).length} ABIs to app/src/generated`);
